# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target ‘Instagram’ do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for ParseChat
    pod ‘Parse’
    pod ‘ParseUI’
    inhibit_all_warnings!
    pod 'MBProgressHUD'
    pod 'JSSAlertView'
    pod 'RKDropdownAlert'
    pod 'Sharaku'
    pod 'RevealingSplashView'

end
